import { Lesson,  } from "./DataStructure"


 export const Data: Array<Lesson> = [
    {
      courseTitle: "Building Scalable APIs with GraphQL",
      status: "Completed",
      totalLectures: 42,
      completedLectures: 36,
      progress: "85%",
      action: "Continue",
    },
    {
      courseTitle: "Create a Design System in Figma",
      status: "Completed",
      totalLectures: 20,
      completedLectures: 20,
      progress: "100%",
      action: "Completed",
    },
    {
      courseTitle: "Data Table",
      status: "In Progress",
      totalLectures: 15,
      completedLectures: 8,
      progress: "53%",
      action: "Continue",
    },
    {

      courseTitle: "The Complete Web Development in Python",
      status: "Not Started",
      totalLectures: 60,
      completedLectures: 0,
      progress: "0%",
      action: "Start",
    },
    {
      courseTitle: "Digital Marketing Masterclass",
      status: "Not Started",
      totalLectures: 35,
      completedLectures: 0,
      progress: "0%",
      action: "Start",
    },
    {
      courseTitle: "Graphic Design Masterclass",
      status: "Not Started",
      totalLectures: 25,
      completedLectures: 0,
      progress: "0%",
      action: "Start",
    },
    {
        courseTitle: "Building Scalable APIs with GraphQL",
        status: "Completed",
        totalLectures: 42,
        completedLectures: 36,
        progress: "85%",
        action: "Continue",
      },
      {
        courseTitle: "Create a Design System in Figma",
        status: "Completed",
        totalLectures: 20,
        completedLectures: 20,
        progress: "100%",
        action: "Completed",
      },
      {
        courseTitle: "Data Table",
        status: "In Progress",
        totalLectures: 15,
        completedLectures: 8,
        progress: "53%",
        action: "Continue",
      },
      {
        courseTitle: "The Complete Web Development in Python",
        status: "Not Started",
        totalLectures: 60,
        completedLectures: 0,
        progress: "0%",
        action: "Start",
      },
      {
        courseTitle: "Digital Marketing Masterclass",
        status: "Not Started",
        totalLectures: 35,
        completedLectures: 0,
        progress: "0%",
        action: "Start",
      },
      {
        courseTitle: "Graphic Design Masterclass",
        status: "Not Started",
        totalLectures: 25,
        completedLectures: 0,
        progress: "0%",
        action: "Start",
      },
      {
        courseTitle: "React Table",
        status: "In Progress",
        totalLectures: 12,
        completedLectures: 5,
        progress: "42%",
        action: "Continue",
      },
      {
        courseTitle: "Next.js Fundamentals",
        status: "Not Started",
        totalLectures: 20,
        completedLectures: 0,
        progress: "0%",
        action: "Start",
      },
      {
        courseTitle: "Full-Stack Web Development with Node.js",
        status: "Completed",
        totalLectures: 45,
        completedLectures: 43,
        progress: "96%",
        action: "Completed",
      },
      {
        courseTitle: "JavaScript: Understanding the Weird Parts",
        status: "In Progress",
        totalLectures: 30,
        completedLectures: 18,
        progress: "60%",
        action: "Continue",
      },
      {
        courseTitle: "TypeScript for Beginners",
        status: "Not Started",
        totalLectures: 10,
        completedLectures: 0,
        progress: "0%",
        action: "Start",
      },
      {
        courseTitle: "Functional Programming in JavaScript",
        status: "Completed",
        totalLectures: 18,
        completedLectures: 18,
        progress: "100%",
        action: "Completed",
      },
      {
        courseTitle: "Building Scalable APIs with GraphQL",
        status: "Completed",
        totalLectures: 42,
        completedLectures: 36,
        progress: "85%",
        action: "Continue",
      },
      {
        courseTitle: "Create a Design System in Figma",
        status: "Completed",
        totalLectures: 20,
        completedLectures: 20,
        progress: "100%",
        action: "Completed",
      },
      {
        courseTitle: "Data Table",
        status: "In Progress",
        totalLectures: 15,
        completedLectures: 8,
        progress: "53%",
        action: "Continue",
      },
      {
  
        courseTitle: "The Complete Web Development in Python",
        status: "Not Started",
        totalLectures: 60,
        completedLectures: 0,
        progress: "0%",
        action: "Start",
      },
      {
        courseTitle: "Digital Marketing Masterclass",
        status: "Not Started",
        totalLectures: 35,
        completedLectures: 0,
        progress: "0%",
        action: "Start",
      },
      {
        courseTitle: "Graphic Design Masterclass",
        status: "Not Started",
        totalLectures: 25,
        completedLectures: 0,
        progress: "0%",
        action: "Start",
      },
      {
          courseTitle: "Building Scalable APIs with GraphQL",
          status: "Completed",
          totalLectures: 42,
          completedLectures: 36,
          progress: "85%",
          action: "Continue",
        },
        {
          courseTitle: "Create a Design System in Figma",
          status: "Completed",
          totalLectures: 20,
          completedLectures: 20,
          progress: "100%",
          action: "Completed",
        },
        {
          courseTitle: "Data Table",
          status: "In Progress",
          totalLectures: 15,
          completedLectures: 8,
          progress: "53%",
          action: "Continue",
        },
        {
          courseTitle: "The Complete Web Development in Python",
          status: "Not Started",
          totalLectures: 60,
          completedLectures: 0,
          progress: "0%",
          action: "Start",
        },
        {
          courseTitle: "Digital Marketing Masterclass",
          status: "Not Started",
          totalLectures: 35,
          completedLectures: 0,
          progress: "0%",
          action: "Start",
        },
        {
          courseTitle: "Graphic Design Masterclass",
          status: "Not Started",
          totalLectures: 25,
          completedLectures: 0,
          progress: "0%",
          action: "Start",
        },
        {
          courseTitle: "React Table",
          status: "In Progress",
          totalLectures: 12,
          completedLectures: 5,
          progress: "42%",
          action: "Continue",
        },
        {
          courseTitle: "Next.js Fundamentals",
          status: "Not Started",
          totalLectures: 20,
          completedLectures: 0,
          progress: "0%",
          action: "Start",
        },
        {
          courseTitle: "Full-Stack Web Development with Node.js",
          status: "Completed",
          totalLectures: 45,
          completedLectures: 43,
          progress: "96%",
          action: "Completed",
        },
        {
          courseTitle: "JavaScript: Understanding the Weird Parts",
          status: "In Progress",
          totalLectures: 30,
          completedLectures: 18,
          progress: "60%",
          action: "Continue",
        },
        {
          courseTitle: "TypeScript for Beginners",
          status: "Not Started",
          totalLectures: 10,
          completedLectures: 0,
          progress: "0%",
          action: "Start",
        },
        {
          courseTitle: "Functional Programming in JavaScript",
          status: "Completed",
          totalLectures: 18,
          completedLectures: 18,
          progress: "100%",
          action: "Completed",
        }
  ];

